/**
 * Ambiances de ciel, une par île. Toutes les couleurs sont interpolées lors
 * des transitions (voir world.setTheme).
 */
export const THEMES = {
  crepuscule: {
    label: 'Crépuscule',
    sky: {
      top: '#2a1f63',
      mid: '#7b4bb3',
      horizon: '#ffaf8c',
      glow: '#ffd9a0',
      below: '#c9779b',
      sun: '#fff1c4',
    },
    fog: '#e79aa6',
    sea: { deep: '#8a5aa8', mid: '#c27fb4', light: '#f2a8b8', foam: '#ffd6c9' },
    hemi: { sky: '#d9ccff', ground: '#7a4a86', intensity: 1.15 },
    key: { color: '#fff0dc', intensity: 2.9 },
    stars: 0.6,
    lanterns: 0.55,
    aurora: 0,
    lightning: false,
  },
  aube: {
    label: 'Aube',
    sky: {
      top: '#4d63c9',
      mid: '#b993e0',
      horizon: '#ffd2b4',
      glow: '#fff0c8',
      below: '#e0a3c2',
      sun: '#fffbea',
    },
    fog: '#f3c4cc',
    sea: { deep: '#9b7cc6', mid: '#d3a2d2', light: '#f6c7d6', foam: '#fff0e8' },
    hemi: { sky: '#e9e2ff', ground: '#a07aa2', intensity: 1.25 },
    key: { color: '#fff3e2', intensity: 2.8 },
    stars: 0.18,
    lanterns: 0.35,
    aurora: 0,
    lightning: false,
  },
  jour: {
    label: 'Zénith',
    sky: {
      top: '#2b74db',
      mid: '#5fb0f4',
      horizon: '#cdeeff',
      glow: '#fffbe0',
      below: '#8fc6e6',
      sun: '#ffffff',
    },
    fog: '#bfe2f6',
    sea: { deep: '#7cb0e4', mid: '#a6d1f4', light: '#d3ebfb', foam: '#ffffff' },
    hemi: { sky: '#e2f3ff', ground: '#6f8c9c', intensity: 1.3 },
    key: { color: '#fffaf0', intensity: 3.1 },
    stars: 0,
    lanterns: 0.2,
    aurora: 0,
    lightning: false,
  },
  orage: {
    label: 'Orage',
    sky: {
      top: '#1d2738',
      mid: '#3d5166',
      horizon: '#93a8b2',
      glow: '#cbd8c4',
      below: '#4b5d6e',
      sun: '#e8f0e0',
    },
    fog: '#7d93a1',
    sea: { deep: '#3b4d61', mid: '#53677b', light: '#788d9e', foam: '#a8bbc5' },
    hemi: { sky: '#b8c8d9', ground: '#3d4656', intensity: 1.15 },
    key: { color: '#e9f0ff', intensity: 2.5 },
    stars: 0.05,
    lanterns: 0.7,
    aurora: 0,
    lightning: true,
  },
  nuit: {
    label: 'Lune',
    sky: {
      top: '#070c2c',
      mid: '#1c2b6c',
      horizon: '#5b60a9',
      glow: '#a9b5ff',
      below: '#2b2f6b',
      sun: '#f3f5ff',
    },
    fog: '#3b3f7a',
    sea: { deep: '#1e2357', mid: '#2e3478', light: '#454c99', foam: '#6e75c3' },
    hemi: { sky: '#8c97ff', ground: '#2d2252', intensity: 1.05 },
    key: { color: '#cdd7ff', intensity: 2.2 },
    stars: 1,
    lanterns: 1,
    aurora: 0,
    lightning: false,
  },
  aurore: {
    label: 'Aurores',
    sky: {
      top: '#071a2c',
      mid: '#0f4a5c',
      horizon: '#4fd6b0',
      glow: '#b8ffde',
      below: '#1d3b5c',
      sun: '#e8fff4',
    },
    fog: '#2c5e6e',
    sea: { deep: '#16324d', mid: '#1f4d66', light: '#2e7083', foam: '#58b8b0' },
    hemi: { sky: '#a6f5e2', ground: '#2d2a5c', intensity: 1.05 },
    key: { color: '#e6fff6', intensity: 2.3 },
    stars: 0.9,
    lanterns: 0.9,
    aurora: 1,
    lightning: false,
  },
};
